// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CBZService centraliza a lógica de manipular arquivos CBZ
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CleanupTempFolder remove a pasta temporária do disco quando o processamento for concluído
 */
export function CleanupTempFolder(folderPath: string): $CancellablePromise<void> {
    return $Call.ByID(3538748139, folderPath);
}

/**
 * ProcessCBZ recebe o nome e os bytes do CBZ enviado pelo frontend, redimensiona
 * todas as imagens para a largura/altura informadas e retorna os bytes do novo CBZ.
 */
export function ProcessCBZ(fileName: string, fileData: string | null, width: number, height: number): $CancellablePromise<string | null> {
    return $Call.ByID(706764513, fileName, fileData, width, height);
}

/**
 * SaveCBZ grava os bytes do CBZ processado no caminho escolhido pelo usuário
 */
export function SaveCBZ(outputPath: string, fileData: string | null): $CancellablePromise<void> {
    return $Call.ByID(4078204839, outputPath, fileData);
}

/**
 * UnpackCBZ recebe o nome e os bytes do arquivo enviado pelo frontend,
 * extrai na pasta temporária do sistema e retorna as informações dos arquivos descompactados.
 */
export function UnpackCBZ(fileName: string, fileData: string | null): $CancellablePromise<$models.ExtractedCBZ | null> {
    return $Call.ByID(1984647430, fileName, fileData);
}
