// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CBZProgress descreve o andamento do processamento emitido ao frontend via
 * o evento "cbz:progress". A porcentagem é calculada com base nas páginas
 * já processadas em relação ao total.
 */
export interface CBZProgress {
    "percentage": number;
    "page": number;
    "total": number;
    "stage": string;
    "message": string;
}

/**
 * ExtractedCBZ contém o resultado da extração para retornar ao frontend
 */
export interface ExtractedCBZ {
    "tempFolder": string;
    "pageCount": number;
    "files": string[] | null;
}
